### ISSUE TITLE
The service "Luzrain\TelegramBotApi\BotApi" has a dependency on a non-existent service "GuzzleHttp\Psr7\HttpFactory".

### ISSUE THREAD

**Issue by Rorkh** [luzrain/telegram-bot-bundle#1]
Got the
`The service "Luzrain\TelegramBotApi\BotApi" has a dependency on a non-existent service "GuzzleHttp\Psr7\HttpFactory".`
Error after installation.

**Comment by luzrain** [comment]
Please ensure that you have installed Guzzle HTTP client if you are using the configuration from readme example.  
You also need to configure the services that you reference in _telegram_bot.yaml_  (_GuzzleHttp\ClientInterface_ and _GuzzleHttp\Psr7\HttpFactory_ should be services).
Here is an example of the Guzzle HTTP configuration that you need to put in your _services.yaml_ in advance:
```php
#config/services.yaml

services:
    GuzzleHttp\ClientInterface:
        class: GuzzleHttp\Client
        arguments:
            - http_errors: false

    GuzzleHttp\Psr7\HttpFactory:
        class: GuzzleHttp\Psr7\HttpFactory
```
